// const CopyWebpackPlugin = require('copy-webpack-plugin');
// const dotenv = require('dotenv');
// const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
// const HtmlWebpackPlugin = require('html-webpack-plugin');
// const path = require('path');
// const createStyledComponentsTransformer = require('typescript-plugin-styled-components').default;
// const { DefinePlugin } = require('webpack');
// const { baseConfig } = require('./webpack.base.config');

// const styledComponentsTransformer = createStyledComponentsTransformer();

// const devSpecificConfig = baseConfig({
//   mode: 'development',
//   entry: [
//     path.join(process.cwd(), 'app/app.js') // Start with js/app.js
//   ],

//   // Don't use hashes in dev mode for better performance
//   output: {
//     chunkFilename: '[name].chunk.js'
//   },

//   optimization: {
//     splitChunks: {
//       chunks: 'all'
//     }
//   },

//   // Add development plugins
//   plugins: [
//     new HtmlWebpackPlugin({
//       inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
//       template: 'app/index.html'
//     }),
//     // new CircularDependencyPlugin({
//     //   exclude: /a\.js|node_modules/, // exclude node_modules
//     //   failOnError: false // show a warning when there is a circular dependency
//     // }),
//     new ForkTsCheckerWebpackPlugin({
//       async: true,
//       typescript: {
//         memoryLimit: 5000
//       }
//     })
//   ],
//   tsLoaders: [
//     { loader: 'babel-loader' }, // using babel after typescript transpiles to target es6
//     {
//       loader: 'ts-loader',
//       options: {
//         transpileOnly: true, // fork-ts-checker-webpack-plugin is used for type checking
//         logLevel: 'info',
//         getCustomTransformers: () => ({
//           before: [styledComponentsTransformer]
//         })
//       }
//     }
//   ],

//   devtool: 'eval-source-map',

//   performance: {
//     hints: false
//   },

//   // Webpack 5 dev middleware
//   devServer: {
//     static: path.join(__dirname, 'build'),
//     historyApiFallback: true,
//     port: 3000,
//     open: false,
//     hot: true
//   },
//   stats: {
//     warnings: false
//   }
// });

// module.exports = devSpecificConfig;
